
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bayro
 */
public class PrimerSerie extends javax.swing.JFrame {

    /**
     * Creates new form PrimerSerie
     */
    public PrimerSerie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresandoconversion = new javax.swing.JTextField();
        conversiona = new javax.swing.JComboBox<>();
        conversion = new javax.swing.JComboBox<>();
        convertir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        respuesta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conversiona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GTQ", "USD", "EUR", "PESO MX" }));
        conversiona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversionaActionPerformed(evt);
            }
        });

        conversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GTQ", "USD", "EUR", "PESO MX" }));
        conversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversionActionPerformed(evt);
            }
        });

        convertir.setText("CONVERTIR");
        convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 3, 18)); // NOI18N
        jLabel1.setText("Convertir a:");

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 3, 18)); // NOI18N
        jLabel2.setText("Introduce importe:");

        respuesta.setColumns(20);
        respuesta.setFont(new java.awt.Font("Myanmar Text", 3, 18)); // NOI18N
        respuesta.setRows(5);
        jScrollPane1.setViewportView(respuesta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conversiona, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(convertir, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ingresandoconversion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(conversion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conversion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresandoconversion))
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertir)
                    .addComponent(conversiona, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conversionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversionaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conversionaActionPerformed

    private void conversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conversionActionPerformed

    private void convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirActionPerformed
 
          respuesta.setText("");   
  
        Double dato;
        Double cantidad = Double.parseDouble(ingresandoconversion.getText());
        
        
        if("USD".equals(conversion.getSelectedItem().toString()) && "USD".equals(conversiona.getSelectedItem().toString()))
        {  
        dato = cantidad;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        else if ("USD".equals(conversion.getSelectedItem().toString()) && "GTQ".equals(conversiona.getSelectedItem().toString()))
        {  
        dato = cantidad * 7.67;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        else if ("USD".equals(conversion.getSelectedItem().toString()) && "EUR".equals(conversiona.getSelectedItem().toString()))
        {
        dato = cantidad * 0.95;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        else if ("USD".equals(conversion.getSelectedItem().toString()) && "PESO MX".equals(conversiona.getSelectedItem().toString()))
        {
        dato = cantidad * 20.43;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
     
        if("GTQ".equals(conversion.getSelectedItem().toString()) && "GTQ".equals(conversiona.getSelectedItem().toString()))
        {  
        dato = cantidad;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        else if ("GTQ".equals(conversion.getSelectedItem().toString()) && "USD".equals(conversiona.getSelectedItem().toString()))
        {  
        dato = cantidad * 0.13;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        else if ("GTQ".equals(conversion.getSelectedItem().toString()) && "EUR".equals(conversiona.getSelectedItem().toString()))
        {
        dato = cantidad * 0.12;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        else if ("GTQ".equals(conversion.getSelectedItem().toString()) && "PESO MX".equals(conversiona.getSelectedItem().toString()))
        {
        dato = cantidad * 2.67;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
                
                
                
                
                                
        if("EUR".equals(conversion.getSelectedItem().toString()) && "EUR".equals(conversiona.getSelectedItem().toString()))
        {  
        dato = cantidad;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        else if ("EUR".equals(conversion.getSelectedItem().toString()) && "USD".equals(conversiona.getSelectedItem().toString()))
        {  
        dato = cantidad * 1.05;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        else if ("EUR".equals(conversion.getSelectedItem().toString()) && "GTQ".equals(conversiona.getSelectedItem().toString()))
        {
        dato = cantidad * 8.07;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        else if ("EUR".equals(conversion.getSelectedItem().toString()) && "PESO MX".equals(conversiona.getSelectedItem().toString()))
        {
        dato = cantidad * 21.50;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        
        
        
        
        if("PESO MX".equals(conversion.getSelectedItem().toString()) && "PESO MX".equals(conversiona.getSelectedItem().toString()))
        {  
        dato = cantidad;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        else if ("PESO MX".equals(conversion.getSelectedItem().toString()) && "USD".equals(conversiona.getSelectedItem().toString()))
        {  
        dato = cantidad * 0.049;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        else if ("PESO MX".equals(conversion.getSelectedItem().toString()) && "GTQ".equals(conversiona.getSelectedItem().toString()))
        {
        dato = cantidad * 0.38;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
        
        else if ("PESO MX".equals(conversion.getSelectedItem().toString()) && "EUR".equals(conversiona.getSelectedItem().toString()))
        {
        dato = cantidad * 0.047;
        respuesta.append("Resultado:  "+dato+ " "+ conversiona.getSelectedItem());
    }
   
                
                
    }//GEN-LAST:event_convertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimerSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimerSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimerSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimerSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimerSerie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> conversion;
    private javax.swing.JComboBox<String> conversiona;
    private javax.swing.JButton convertir;
    private javax.swing.JTextField ingresandoconversion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea respuesta;
    // End of variables declaration//GEN-END:variables
}
